### ISSUE TITLE
Replace cnfldemos/kafka-connect-datagen with confluentinc/cp-kafka-connect

### ISSUE THREAD

**Issue by echang0929** [confluentinc/cp-all-in-one#32]
I've tried to replace image in "cp-all-in-one/cp-all-in-one-community/docker-compose.yml"  cnfldemos/kafka-connect-datagen:0.3.2-5.5.0 with confluentinc/cp-kafka-connect:5.5.1, and provided some commands to add datagen package: 

````
  connect:
    image: confluentinc/cp-kafka-connect:5.5.1
    hostname: connect
    container_name: connect
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    ports:
      - "8083:8083"
    command:
      - sh
      - -exc
      - |
        confluent-hub install --no-prompt --component-dir /usr/share/confluent-hub-components/ confluentinc/kafka-connect-datagen:latest
        exec /etc/confluent/docker/run
````

So that this community cluster apply the latest version of kafka-connect. I've exercised all steps in tutorial doc https://docs.confluent.io/current/quickstart/cos-docker-quickstart.html successfully.
