### ISSUE TITLE
Exit code 1 for multiple containers, missing Dockerfile

### ISSUE THREAD

**Issue by marcin2x4** [confluentinc/cp-all-in-one#53]
Below services end with `Exit 1` code: 

- broker   
- ksql-datagen   
- rest-proxy

I tried adding memory limit but no luck, should these be placed in specific line of docker-compose file?

```
deploy:
      resources:
        limits:
          cpus: xxx
          memory: xxx
        reservations:
          cpus: xxx
          memory: xxx
```

Also I would suggest to add to each docker-compose a `Dockerfile` as well.
